/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayCategoryModeRouteImport } from './routes/play.$category.$mode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCategoryModeRoute = PlayCategoryModeRouteImport.update({
  id: '/play/$category/$mode',
  path: '/play/$category/$mode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play/$category/$mode': typeof PlayCategoryModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play/$category/$mode': typeof PlayCategoryModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play/$category/$mode': typeof PlayCategoryModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play/$category/$mode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play/$category/$mode'
  id: '__root__' | '/' | '/play/$category/$mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayCategoryModeRoute: typeof PlayCategoryModeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$category/$mode': {
      id: '/play/$category/$mode'
      path: '/play/$category/$mode'
      fullPath: '/play/$category/$mode'
      preLoaderRoute: typeof PlayCategoryModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayCategoryModeRoute: PlayCategoryModeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
